api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : lib
env_make   : ~
env_prep   : get-composer
env_post   : ci-coveralls,ci-codacy
php_conf   : timezone
php_exts   : ~
app_prep   : dep-composer
app_post   : ~
app_path   : ~
pkg_name   : augustus-file-library
pkg_desc   : "implementations on top of SplFileInfo that includes size helpers and temp files with automatic removal on script completion"
pkg_bndl   : false
